---
driver:
  name: terraform
  variable_files:
    - testing.tfvars

provisioner:
  name: terraform

platforms:
  - name: ubuntu

verifier:
  name: terraform
  systems:
    - name: default
      backend: ssh
      hosts_output: ec2_machines
      key_files:
        - /path/to/your/<pem_key_file>.pem


suites:
  - name: default
